# Generated by Django 4.2.1 on 2023-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoEmp',
            fields=[
                ('id_cargo_emp', models.FloatField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo_emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.FloatField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.FloatField(primary_key=True, serialize=False)),
                ('dv_rut', models.CharField(max_length=1)),
                ('p_nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(max_length=50)),
                ('s_apellido', models.CharField(max_length=50)),
                ('p_apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.FloatField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('n_direccion', models.FloatField()),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoR',
            fields=[
                ('id_estado', models.FloatField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_r',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoS',
            fields=[
                ('id_estado_solicitud', models.FloatField(primary_key=True, serialize=False)),
                ('estado_solicitud', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id_piso', models.FloatField(primary_key=True, serialize=False)),
                ('piso', models.FloatField()),
            ],
            options={
                'db_table': 'piso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.FloatField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'prioridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.FloatField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_repote', models.FloatField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.FloatField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.FloatField(primary_key=True, serialize=False)),
                ('solicitud', models.CharField(max_length=50)),
                ('attribute_3', models.DateField()),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
